workflows:
  main:
    name: Build IPA
    scripts:
      - echo "Building the app"
      - flutter clean
      - flutter build ios --release --no-codesign
      - echo "Exporting the IPA file"  
    artifacts:
      - build/ios/outputs/ipa/Runner.ipa
