workflows:
  main:
    name: Build IPA
    scripts:
      - echo "Building the app"
      - flutter clean
      - flutter build ios --release --no-codesign
      - echo "Exporting the IPA file"
      - mkdir -p $CM_ARTIFACTS_DIR/build/ios/outputs/ipa/
      - mv build/ios/iphoneos/Runner.ipa $CM_ARTIFACTS_DIR/build/ios/outputs/ipa/
    artifacts:
      - build/ios/outputs/ipa/Runner.ipa
