workflows:
  build:
    scripts:
      - echo "Building iOS app..."
      - xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release -archivePath build/Runner.xcarchive archive
      - xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build --force
    artifacts:
      - build/*.ipa
