workflows:
  ios:
    name: iOS Workflow
    environment:
      xcode: latest
    scripts:
      - |
        set -eo pipefail
        xcodebuild -workspace YourProject.xcworkspace -scheme YourScheme -sdk iphoneos -configuration Release -archivePath build/YourProject.xcarchive archive | xcpretty
        xcodebuild -exportArchive -archivePath build/YourProject.xcarchive -exportPath build -exportOptionsPlist ExportOptions.plist | xcpretty
      - |
        cd build
        ls
    artifacts:
      - build/*.ipa
