workflows:
  main:
    name: Build IPA
    scripts:
      - echo "Building the app"
      - flutter clean
      - flutter build ios --release --no-codesign
      - echo "Creating output directory"
      - mkdir -p "$CM_ARTIFACTS_DIR/outputs/ipa"
      - echo "Exporting the IPA file"
      - cp build/ios/outputs/ipa/Runner.ipa "$CM_ARTIFACTS_DIR/outputs/ipa/Runner.ipa"
    artifacts:
      - outputs/ipa/Runner.ipa
